title: "Your Name"
description: "My CV and Portfolio"
url: "https://xyz.github.io"   # replace xyz with your GitHub username
baseurl: ""

remote_theme: "piazzai/cvless"

author:
  name: "Your Name"
  email: "you@example.com"
  github: "xyz"
  linkedin: "your-linkedin"
  twitter: "your-twitter"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
