title: "Kankana Shukla"
description: "My CV and Portfolio"
url: "https://kankana.github.io"   # replace xyz with your GitHub username
baseurl: ""

remote_theme: "piazzai/cvless"

cvless:
  skin: dark

author:
  name: "Kankana Shukla"
  email: "shukla.kank@gmail.com"
  github: "https://github.com/kankanashukla"
  linkedin: "https://www.linkedin.com/in/kankanashukla/"
  twitter: "your-twitter"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
